config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'
  get 'say/goodbye'
  get 'say/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
  end

  def goodbye
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/goodbye.html.erb
<h1>Goodbye!</h1> ​ 
<p>It was nice having you here.</p>

<p>
  Say <a href="/say/hello">Hello</a>
</p>

<p>
  Say <%= link_to("Hello", say_hello_path) %>
</p>

app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>

<p>
 The time is <%= @time %>
</p>

<p>
  Say <a href="/say/goodbye">Goodbye</a> with anchor tag and relative path.
</p>
<p>
  Say <%= link_to("Goodbye", say_goodbye_path) %> with link_to() and rails generated path variable.
</p>

app/views/say/index.html.erb
<p>
  Say <%= link_to("Hello", say_hello_path) %>
</p>

<p>
  Say <%= link_to("Goodbye", say_goodbye_path) %> with link_to() and rails generated path variable.
</p>